config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users
  resources :locations
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address
  after_validation :geocode

  def address
    [comuna, region, "Chile"].compact.join(', ')
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /locations
  # GET /locations.json
  def index
    
    @locations = Location.all
    @conections = Conection.all
    cont =  @locations.length()

    @geojson = Array.new

    @locations.each do |location|
      if location.latitude
        #puts location.address
        cont -= 1
      end

      info = {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [location.longitude, location.latitude]
        },
        properties: {
          sistema: location.sistema, 
          subsistema: location.subsistema, 
          propietario: location.propietario, 
          rut: location.rut, 
          nombre_central: location.nombre_central, 
          estado: location.estado, 
          fecha_puesta_servicio_central: location.fecha_puesta_servicio_central, 
          address: location.address, 
          clasificacion: location.clasificacion, 
          tipo_energia: location.tipo_energia, 
          potencia_bruta_mw: location.potencia_bruta_mw, 
          potencia_neta_mw: location.potencia_neta_mw, 
          medio_generacion: location.medio_generacion, 
          distribuidora: location.distribuidora, 
          punto_conexion: location.punto_conexion, 
          combustible: location.combustible, 
          consumo: location.consumo, 
          unidad_consumo: location.unidad_consumo,
          :'marker-color' => '#00607d',
          :'marker-symbol' => 'circle',
          :'marker-size' => 'medium'
        }
      }
      if location.sistema.nil?
        info[:properties]['marker-size'] = 'small'
        info[:properties]['marker-symbol'] = 'p'
      end

      if location.tipo_energia == "Solar"
        info[:properties]['marker-color'] = '#fff947'
      elsif location.tipo_energia == "Petróleo Diesel"
        info[:properties]['marker-color'] = '#24291b'
      elsif location.tipo_energia == "Eólica"
        info[:properties]['marker-color'] = '#b1ff87'
      elsif location.tipo_energia == "Hidráulica Pasada"
        info[:properties]['marker-color'] = '#104c7a'
      elsif location.tipo_energia == "Mini Hidráulica Pasada"
        info[:properties]['marker-color'] = '#104c7a'
      elsif location.tipo_energia == "Biogas"
        info[:properties]['marker-color'] = '#73777a'
      elsif location.tipo_energia == "Biomasa"
        info[:properties]['marker-color'] = '#cfbb82'
      elsif location.tipo_energia == "Biomasa-Petróleo N°6"
        info[:properties]['marker-color'] = '#a09dd4'
      elsif location.tipo_energia == "Geotérmica"
        info[:properties]['marker-color'] = '#e8af10'
      end
      @geojson << info
    end

    cont2 = 0
    cont3 = 0

    @list_conections = Array.new
    @conections.each do |con|
      if !(@list_conections.include?(con.address))
        @list_conections.push(con.address)
        #puts "Agregando" + con.address + " a las conexiones"
        info = {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [con.longitude, con.latitude]
          },
          properties: {
            conection: "Conexion",
            punto_conexion: con.punto_conexion, 
            centrales: [con.nombre_central],
            sistema: con.sistema, 
            subsistema: con.subsistema, 
            potencia_neta_mw_total: con.potencia_neta_mw.sub(",",".").to_f,
            :'marker-color' => '#00607d',
            :'marker-symbol' => 'circle',
            :'marker-size' => 'large'
          }
        }
        @geojson << info
      else
        @geojson.each do |inf| 
          if inf[:properties][:punto_conexion] == con.punto_conexion && inf[:properties][:conection].present?
            #puts "Agregando" + con.nombre_central + " a las conexion " + inf[:properties][:punto_conexion]
            inf[:properties][:centrales].push(con.nombre_central)
            inf[:properties][:potencia_neta_mw_total] += con.potencia_neta_mw.sub(",",".").to_f
          end
        end
      end
    end
    
    respond_to do |format|
      format.html
      format.json { render json: @geojson }  # respond with the created JSON object
      format.js
    end
  end


  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:comuna, :region, :latitude, :longitude, :tipo_energia, :medio_generacion, :potencia_neta_mw)
    end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>

  <div class="field">
    <%= form.label :comuna %>
    <%= form.text_field :comuna %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :long %>
    <%= form.text_field :long %>
  </div>

  <div class="field">
    <%= form.label :tipo_energia %>
    <%= form.text_field :tipo_energia %>
  </div>

  <div class="field">
    <%= form.label :medio_generacion %>
    <%= form.text_field :medio_generacion %>
  </div>

  <div class="field">
    <%= form.label :potencia_neta_mw %>
    <%= form.text_field :potencia_neta_mw %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
 

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comuna:</strong>
  <%= @location.comuna %>
</p>

<p>
  <strong>Region:</strong>
  <%= @location.region %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Long:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>Tipo energia:</strong>
  <%= @location.tipo_energia %>
</p>

<p>
  <strong>Medio generacion:</strong>
  <%= @location.medio_generacion %>
</p>

<p>
  <strong>Potencia neta mw:</strong>
  <%= @location.potencia_neta_mw %>
</p>

<header><h1 class="display-4"><%= @location.comuna %></h1></header>

<p>Address: <%= @location.address %></p>
<p>Coordinates: <%= @location.latitude %> <%= @location.longitude %></p>

<body>
  <div id="energy_map" class="clearfix">
    <div class="container text center">
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1 text-center">
          <div class="">
            <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@location.latitude},#{@location.longitude}&markers=#{@location.latitude},#{@location.longitude}&zoom=7&size=640x400&key=AIzaSyA4Ni00te13MNuaxQ6NRoXzUQV0MZA0jis",
              class: 'img-fluid img-rounded', alt: "#{@location.comuna} on the map"%>
            </div>
          </div>
        </div>
    </div>
  </div>
  

  
</body>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>